export enum Tag {
  DESIGN = "DESIGN",
  HOMEWORK = "HOMEWORK",
  ASSIGNMENT = "ASSIGNMENT",
  DEPLOYMENT = "DEPLOYMENT",
  GIT = "GIT",
  DATABASE = "DATABASE",
  MINI_PROJECT = "MINI_PROJECT",
  DOCUMENTATION = "DOCUMENTATION",
  FEATURE = "FEATURE",
}
